import { sql, type Kysely } from "kysely";

/**
 * Better Auth tables, isolated in their own `auth` schema.
 *
 * SQL generated by `bunx auth generate` against the config in `src/lib/auth.ts`
 * (email + password, admin plugin). Copied verbatim so the schema is frozen in
 * time and never depends on the installed better-auth version at runtime.
 *
 * Keeping auth in a separate schema means pgbase (which exposes `public`) can
 * never route to these tables — the REST surface is structurally blind to
 * credentials, sessions and accounts.
 *
 * To regenerate after changing auth config:
 *   1. point `auth.generate.ts` at a scratch database with `schemaName: "auth"`
 *   2. bunx auth generate --adapter kysely --output ./schema.sql -y
 *   3. diff and paste the new statements here.
 */
export async function up(db: Kysely<any>): Promise<void> {
  await sql.raw(`
    create schema if not exists "auth";

    create table "auth"."user" (
      "id" text not null primary key,
      "name" text not null,
      "email" text not null unique,
      "emailVerified" boolean not null,
      "image" text,
      "createdAt" timestamptz default CURRENT_TIMESTAMP not null,
      "updatedAt" timestamptz default CURRENT_TIMESTAMP not null,
      "role" text,
      "banned" boolean,
      "banReason" text,
      "banExpires" timestamptz
    );

    create table "auth"."session" (
      "id" text not null primary key,
      "expiresAt" timestamptz not null,
      "token" text not null unique,
      "createdAt" timestamptz default CURRENT_TIMESTAMP not null,
      "updatedAt" timestamptz not null,
      "ipAddress" text,
      "userAgent" text,
      "userId" text not null references "auth"."user" ("id") on delete cascade,
      "impersonatedBy" text
    );

    create table "auth"."account" (
      "id" text not null primary key,
      "accountId" text not null,
      "providerId" text not null,
      "userId" text not null references "auth"."user" ("id") on delete cascade,
      "accessToken" text,
      "refreshToken" text,
      "idToken" text,
      "accessTokenExpiresAt" timestamptz,
      "refreshTokenExpiresAt" timestamptz,
      "scope" text,
      "password" text,
      "createdAt" timestamptz default CURRENT_TIMESTAMP not null,
      "updatedAt" timestamptz not null
    );

    create table "auth"."verification" (
      "id" text not null primary key,
      "identifier" text not null,
      "value" text not null,
      "expiresAt" timestamptz not null,
      "createdAt" timestamptz default CURRENT_TIMESTAMP not null,
      "updatedAt" timestamptz default CURRENT_TIMESTAMP not null
    );

    create index "session_userId_idx" on "auth"."session" ("userId");
    create index "account_userId_idx" on "auth"."account" ("userId");
    create index "verification_identifier_idx" on "auth"."verification" ("identifier");
  `).execute(db);
}

export async function down(db: Kysely<any>): Promise<void> {
  await sql.raw(`drop schema if exists "auth" cascade`).execute(db);
}
